before_install: 
 - cd SpringBootMySQLApp
 - chmod +x mvnw
 - mysql -e 'create database filmoteka;'
 - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('1234') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
sudo: required
dist: trusty
services:
  - mysql
language: java
jdk:
 - oraclejdk8
 install: true
 addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

